### ISSUE TITLE
CONNECTION FAILED if domain same localhost

### ISSUE THREAD

**Issue by zpcol** [davidgoy/reflect#2]
domain of WordPress site to fetch content from mydomain.name (localhost)
domain reflect-app.name (localhost)

**Comment by davidgoy** [comment]
Thanks very much for your feedback.

Reflect 1.0.0-beta.10 currently works only if the WordPress site is not on localhost.

I will look into this limitation for the next release.

Cheers!

**Comment by davidgoy** [comment]
I can confirm that Reflect v1.0.0-beta.10 can currently fetch data from WP site hosted on localhost but only if it's on _http_ and **not** _https_.

That means Reflect currently won't fetch data from a locally hosted WordPress site that uses self-signed SSL certificate.

For the next version, I will see if I can add the ability for Reflect to fetch data from a WP site on localhost that also uses a self-signed SSL cert.

**Comment by davidgoy** [comment]
Reflect v1.0.0-beta.11 now allows connection to a WordPress site that uses self-signed SSL certificate.
